project_id = "ouxqcdtspedbwpceemfc"

[functions.support-inbound-webhook]
verify_jwt = false

[functions.invite-customer]
verify_jwt = false

[functions.sales-inbound-webhook]
verify_jwt = false

[functions.invoice-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false