import React, { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Loader2, Upload, X, File } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import SubscriptionRequiredAlert from '@/components/portal/SubscriptionRequiredAlert';
import { useAuth } from '@/contexts/AuthContext';
import { useLanguage } from '@/contexts/LanguageContext';
import { useSubscription } from '@/hooks/use-subscription';
import { supabase } from '@/integrations/supabase/client';

interface PendingFile {
  file: File;
  id: string;
}

const NewTicket: React.FC = () => {
  const { user, customerData, loading } = useAuth();
  const { isSubscribed, loading: subscriptionLoading } = useSubscription();
  const navigate = useNavigate();
  const { toast } = useToast();
  const { t } = useLanguage();
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [pendingFiles, setPendingFiles] = useState<PendingFile[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (!loading && !user) {
      navigate('/login');
    }
    // Redirect non-subscribers back to tickets list
    if (!loading && !subscriptionLoading && !isSubscribed && customerData) {
      navigate('/portal/tickets');
    }
  }, [user, loading, navigate, isSubscribed, subscriptionLoading, customerData]);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    const newFiles = files.map((file) => ({
      file,
      id: crypto.randomUUID(),
    }));
    setPendingFiles((prev) => [...prev, ...newFiles]);
    
    // Reset input
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const removeFile = (id: string) => {
    setPendingFiles((prev) => prev.filter((f) => f.id !== id));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user || !customerData) return;
    
    setIsSubmitting(true);

    try {
      // Create ticket (ticket_number is auto-generated by database trigger)
      const { data: ticket, error: ticketError } = await supabase
        .from('tickets')
        .insert({
          customer_id: customerData.id,
          created_by: user.id,
          title: title.trim(),
          status: 'submitted',
        })
        .select()
        .single();

      if (ticketError) throw ticketError;

      // Create initial comment
      const { data: comment, error: commentError } = await supabase
        .from('ticket_comments')
        .insert({
          ticket_id: ticket.id,
          author_user_id: user.id,
          author_email: user.email,
          author_type: 'customer',
          source: 'portal',
          body_markdown: description.trim(),
        })
        .select()
        .single();

      if (commentError) throw commentError;

      // Upload attachments
      for (const { file } of pendingFiles) {
        const fileName = `${crypto.randomUUID()}-${file.name}`;
        const storagePath = `customer/${customerData.id}/ticket/${ticket.id}/${fileName}`;

        const { error: uploadError } = await supabase.storage
          .from('ticket-attachments')
          .upload(storagePath, file);

        if (uploadError) {
          console.error('Error uploading file:', uploadError);
          continue;
        }

        await supabase.from('ticket_attachments').insert({
          ticket_id: ticket.id,
          comment_id: comment.id,
          storage_path: storagePath,
          filename: file.name,
          content_type: file.type,
          size_bytes: file.size,
        });
      }

      // Send notification email (via edge function)
      try {
        await supabase.functions.invoke('ticket-notification', {
          body: {
            ticketId: ticket.id,
            action: 'created',
          },
        });
      } catch (notifyError) {
        console.error('Error sending notification:', notifyError);
        // Don't fail the ticket creation if notification fails
      }

      toast({
        title: t('Ärende skapat', 'Ticket created'),
        description: t('Ditt supportärende har skickats in.', 'Your support ticket has been submitted.'),
      });

      navigate(`/portal/tickets/${ticket.ticket_number}`);
    } catch (error) {
      console.error('Error creating ticket:', error);
      toast({
        title: t('Fel', 'Error'),
        description: error.message || t('Det gick inte att skapa ärendet.', 'Failed to create ticket.'),
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading || subscriptionLoading) {
    return (
      <>
        <div className="flex items-center justify-center min-h-[400px]">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      </>
    );
  }

  // Redirect if no subscription
  if (!isSubscribed) {
    return (
      <>
        <div className="space-y-6 max-w-2xl">
          <h1 className="text-3xl font-medium">{t('Skapa supportärende', 'Create support ticket')}</h1>
          <SubscriptionRequiredAlert />
        </div>
      </>
    );
  }

  if (!customerData) {
    navigate('/portal/tickets');
    return null;
  }

  return (
    <>
      <div className="space-y-6 max-w-2xl">
        <h1 className="text-3xl font-medium">{t('Skapa supportärende', 'Create support ticket')}</h1>

        <Card>
          <CardContent className="pt-6">
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="title" className="text-primary">{t('Rubrik', 'Title')}</Label>
                <Input
                  id="title"
                  placeholder={t('Kort beskrivning av ditt problem', 'Brief description of your issue')}
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  required
                  maxLength={200}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="description" className="text-primary">{t('Beskrivning', 'Description')}</Label>
                <Textarea
                  id="description"
                  placeholder={t('Beskriv ditt problem i detalj. Markdown-formatering stöds.', 'Provide detailed information about your issue. Markdown formatting is supported.')}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  required
                  className="min-h-[200px]"
                />
              </div>

              <div className="space-y-2">
                <Label className="text-primary">{t('Bilagor', 'Attachments')}</Label>
                <div
                  className="border-2 border-dashed border-border rounded-lg p-6 text-center cursor-pointer hover:border-primary/50 transition-colors"
                  onClick={() => fileInputRef.current?.click()}
                >
                  <Upload className="w-8 h-8 mx-auto text-muted-foreground mb-2" />
                  <p className="text-muted-foreground">
                    {t('Dra och släpp filer här, eller klicka för att bläddra', 'Drag and drop files here, or click to browse')}
                  </p>
                  <Button type="button" variant="outline" size="sm" className="mt-2">
                    {t('Välj filer', 'Choose files')}
                  </Button>
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    onChange={handleFileSelect}
                    className="hidden"
                    accept="image/*,text/plain,application/pdf,application/zip,application/gzip,application/json"
                  />
                </div>

                {pendingFiles.length > 0 && (
                  <div className="space-y-2 mt-4">
                    {pendingFiles.map(({ file, id }) => (
                      <div
                        key={id}
                        className="flex items-center justify-between p-2 bg-muted rounded"
                      >
                        <div className="flex items-center gap-2">
                          <File className="w-4 h-4 text-muted-foreground" />
                          <span className="text-sm truncate max-w-xs">{file.name}</span>
                          <span className="text-xs text-muted-foreground">
                            ({(file.size / 1024).toFixed(1)} KB)
                          </span>
                        </div>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() => removeFile(id)}
                        >
                          <X className="w-4 h-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <div className="flex gap-4">
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                  {t('Skicka ärende', 'Submit ticket')}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => navigate('/portal/tickets')}
                >
                  {t('Avbryt', 'Cancel')}
                </Button>
              </div>

              <p className="text-sm text-muted-foreground border-t border-border pt-4">
                {t('Du kan även svara via e-post när ärendet har skapats.', 'You can also reply by email once the ticket is created.')}
              </p>
            </form>
          </CardContent>
        </Card>
      </div>
    </>
  );
};

export default NewTicket;
