import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { diskTree, reach } from './module-graph.ts';

const root = new URL('..', import.meta.url).pathname;
const artifactDir = `${root}/supabase/functions/_shared/planner-wasm`;
export const SOURCE_FILES = [
  'rust-toolchain.toml',
  'planner-core/Cargo.toml',
  'planner-core/Cargo.lock',
  'planner-core/models/Cargo.toml',
  'planner-core/solver/Cargo.toml',
  'planner-core/policy.json',
  'planner-core/recipe.json',
  'scripts/build-planner-wasm.ts',
  'bench/wasm-planner.ts',
  'bench/planner-engine.json',
  'supabase/functions/_shared/planner-wasm/core.ts',
  'supabase/functions/_shared/planner-wasm/ready-problem.ts',
  'supabase/functions/_shared/planner/energy-price-shape.ts',
  'supabase/functions/_shared/planner/device-models.ts',
  'src/lib/planner-bench/score.ts',
  'src/lib/planner-bench/case.ts',
  'supabase/functions/_shared/planner-wasm/probe.ts',
  'supabase/functions/_shared/planner-wasm/ready-schema.ts',
];
export function plannerSourceFiles(repository: string): string[] {
  const files = [
    ...new Set([...SOURCE_FILES, ...reach(diskTree(repository), ['bench/wasm-planner.ts'])]),
  ];
  const walk = (directory: string) => {
    for (const e of readdirSync(join(repository, directory), { withFileTypes: true })) {
      const path = `${directory}/${e.name}`;
      if (e.isDirectory()) walk(path);
      else if (e.isFile() && e.name.endsWith('.rs')) files.push(path);
    }
  };
  for (const dir of ['planner-core/models/src', 'planner-core/solver/src']) walk(dir);
  return files.sort();
}
export function sourceDigest(repository: string): string {
  const hash = createHash('sha256');
  for (const file of plannerSourceFiles(repository)) {
    hash.update(file).update('\0').update(readFileSync(join(repository, file))).update('\0');
  }
  return hash.digest('hex');
}

if (import.meta.main) {
  const home = Deno.env.get('HOME');
  if (!home) throw new Error('Rust build needs HOME to resolve rustup’s standard Cargo directory.');
  const cargoHome = Deno.env.get('CARGO_HOME') ?? join(home, '.cargo');
  const flags = [
    `--remap-path-prefix=${root}=/workspace/`,
    `--remap-path-prefix=${cargoHome}=/cargo`,
  ];
  const build = await new Deno.Command('cargo', {
    cwd: root,
    env: { CARGO_ENCODED_RUSTFLAGS: flags.join('\u001f') },
    args: [
      'build',
      '--manifest-path',
      'planner-core/Cargo.toml',
      '--locked',
      '--release',
      '--target',
      'wasm32-unknown-unknown',
      '--lib',
    ],
    stdout: 'inherit',
    stderr: 'inherit',
  }).spawn().status;
  if (!build.success) Deno.exit(build.code);
  const source = `${root}/planner-core/target/wasm32-unknown-unknown/release/shs_planner_core.wasm`;
  const bytes = await Deno.readFile(source);
  const wasm_sha256 = createHash('sha256').update(bytes).digest('hex');
  await Deno.copyFile(source, `${artifactDir}/solver.wasm`);
  await Deno.writeTextFile(
    `${artifactDir}/artifact.json`,
    JSON.stringify(
      {
        abi: 2,
        wasm_sha256,
        source_sha256: sourceDigest(root),
        rust: '1.99.0',
        target: 'wasm32-unknown-unknown',
        profile: 'release',
        qualification: 'prototype_only',
        path_remapping: true,
        source_files: plannerSourceFiles(root),
      },
      null,
      2,
    ) + '\n',
  );
  await Deno.copyFile(
    `${root}/planner-core/recipe.json`,
    `${root}/supabase/functions/energy-planner-probe/recipe.json`,
  );
  // --use-api cannot bundle static files. A generated import travels through
  // that existing deployment path; this is the same verified binary.
  await Deno.writeTextFile(
    `${artifactDir}/solver-bytes.ts`,
    `// Generated by deno task build:planner-wasm. Do not edit.\nexport const SOLVER_BASE64 = '${
      Buffer.from(bytes).toString('base64')
    }';\n`,
  );
  console.log(`Verified planner artifact: ${bytes.length} bytes, SHA-256 ${wasm_sha256}`);
}
