// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { recoverFromSchemaDrift } from '@/lib/app-recovery';
import { pinFunctionRegion } from '@/lib/function-region';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
// The region the database lives in, so Edge Functions run beside it rather
// than beside whoever happened to click. Unset simply leaves the default
// nearest-the-browser routing in place.
const SUPABASE_FUNCTION_REGION = import.meta.env.VITE_SUPABASE_FUNCTION_REGION;

// A tab loaded before a migration keeps asking for the column list of the
// build it came from, and PostgREST answers every poll with an error nobody in
// the browser reads. The mismatch is reported precisely enough to act on, so
// it is caught here — once, for every query in the app — rather than at each
// call site.
const schemaDriftCodes = new Set([
  '42703', // undefined_column
  '42P01', // undefined_table
  'PGRST202', // no function matches this name and argument list
  'PGRST204', // a written column does not exist
]);

/** Route an Edge Function call to the database's region, whatever the form. */
function toDatabaseRegion(input: RequestInfo | URL): RequestInfo | URL {
  if (!SUPABASE_FUNCTION_REGION) return input;
  if (typeof input === 'string') {
    return pinFunctionRegion(input, SUPABASE_FUNCTION_REGION);
  }
  if (input instanceof URL) {
    return pinFunctionRegion(input.toString(), SUPABASE_FUNCTION_REGION);
  }
  const pinned = pinFunctionRegion(input.url, SUPABASE_FUNCTION_REGION);
  return pinned === input.url ? input : new Request(pinned, input);
}

async function fetchWithSchemaDriftRecovery(
  input: RequestInfo | URL,
  init?: RequestInit,
): Promise<Response> {
  const response = await fetch(toDatabaseRegion(input), init);
  if (response.status !== 400 && response.status !== 404) return response;
  if (!response.headers.get('content-type')?.includes('json')) return response;

  try {
    const body: unknown = await response.clone().json();
    const code = (body as { code?: unknown } | null)?.code;
    if (typeof code === 'string' && schemaDriftCodes.has(code)) {
      recoverFromSchemaDrift();
    }
  } catch {
    // A body that will not parse says nothing about the schema. The caller
    // still receives the untouched response.
  }
  return response;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: fetchWithSchemaDriftRecovery },
});
